### ISSUE TITLE
Página inicial

### ISSUE THREAD

**Issue by bmarchete** [brunotguima/WhyBuy#2]
Acredito que ao invés de ter uma foto do maps, você já poderia colocar realmente o maps trazendo algumas promoções baseadas na localização do usuário.

Os links para contatos não estão funcionando

Tem bla bla bla na página

**Comment by brunotguima** [comment]
O propósito do banner do maps é realmente apenas apresentar a aplicação, a idéia inicial é manter o maps funcionando apenas no aplicativo mobile. As pendências dá pagina estão sendo arrumadas.
