### ISSUE TITLE
Página sobre nós

### ISSUE THREAD

**Issue by bmarchete** [brunotguima/WhyBuy#4]
A página é bem infantil, com um texto gigante no meio, um monte de fotos sequenciais sem nenhuma descrição. Se for ficar assim, sugiro que removam ela

**Comment by brunotguima** [comment]
OK, em modificação.

**Comment by bmarchete** [comment]
Preto no laranja não deu um bom contraste. Ainda acredito que vocês podiam fazer colunas para mostrar tão pouca informação!
