### ISSUE TITLE
Página de suporte

### ISSUE THREAD

**Issue by bmarchete** [brunotguima/WhyBuy#5]
Texto inicial desproporcional ao resto da página

Fui usar a página e encontrei esse erro! Vocês sabem me dizer porque?
![image](https://user-images.githubusercontent.com/5762205/30116221-5cc528d2-92f3-11e7-86f6-900f7c28703f.png)

**Comment by brunotguima** [comment]
O erro acontecia por causa de uma pendência de package do composer, já foi arrumado.

**Comment by bmarchete** [comment]
Após o envio de uma mensagem, não recebi nenhuma notificação de email recebido!

**Comment by brunotguima** [comment]
Foi mostrado para vocês no momento da análise o envio da mensagem.
